package com.myapp.struts;
// Generated 13 Oct, 2015 4:47:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Student generated by hbm2java
 */
public class Student extends org.apache.struts.validator.ValidatorActionForm implements java.io.Serializable {


     private int id;
     private String name;
     private String password;
     private String phone;
     private String email;

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String name, String password, String phone, String email) {
       this.id = id;
       this.name = name;
       this.password = password;
       this.phone = phone;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


